"""Every number that appears in the submission, emitted as markdown from the results.

Nothing in the proposal, the deck, the film or the technical note is typed by hand.
This script is the only path from `results/` into those documents.

Usage:  python scripts/07_report.py > ../09_RESULTS.md
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

sys.stdout.reconfigure(encoding="utf-8")

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from mizan import config as C

RES = ROOT / "results"
ORDER = ["ET", "A", "B", "C", "D", "E", "F", "G", "SAT", "HS3", "HS", "H",
         "M", "HM1", "HM3"]
LABEL = {
    "ET": "evapotranspiration only",
    "A": "heads only",
    "B": "gravity only",
    "C": "deformation only",
    "D": "evapotranspiration + heads",
    "E": "evapotranspiration + gravity",
    "F": "evapotranspiration + deformation",
    "G": "heads + gravity + deformation",
    "H": "**all four, coupled closure**",
    "SAT": "**satellites only, no wells at all**",
    "HS": "all four, 10 wells instead of 97",
    "HS3": "all four, 3 wells instead of 97",
    "M": "meters on every district, no satellites",
    "HM1": "all four, plus one metered district",
    "HM3": "all four, plus three metered districts",
}


def load(name):
    p = RES / name
    return json.loads(p.read_text()) if p.exists() else None


def section(title):
    print(f"\n## {title}\n")


def main():
    tr = np.load(RES / "truth.npz")
    ab = load("ablation.json")
    al = load("allocation.json")
    vo = load("voi.json")
    de = load("detection.json")
    cv = load("convergence.json")
    eb = load("error_budget.json")

    print("# 09. Results\n")
    print("Generated by `mizan/scripts/07_report.py` from the frozen repository. Every")
    print("number in the proposal, the deck, the film and the technical note comes from")
    print("here and from nowhere else.\n")

    section("The test basin")
    sd = tr["storage_depletion"][-1]
    perm = float(tr["permanent_loss"])
    print(f"| Quantity | Value |")
    print(f"|---|---|")
    print(f"| Domain | {C.DOMAIN_KM:.0f} x {C.DOMAIN_KM:.0f} km, two layers, "
          f"{C.NYEAR} years, {C.NPER} monthly stress periods |")
    print(f"| Truth grid / estimator grid | "
          f"{C.TRUTH.delr_m/1000:.0f} km / {C.EST.delr_m/1000:.0f} km |")
    print(f"| Districts | {C.NDIST} |")
    print(f"| Total abstraction | {tr['q_annual'].sum()/1e9:.2f} km3 "
          f"({tr['q_annual'].sum(0).mean()/1e6:.0f} Mm3/yr) |")
    print(f"| Storage depleted | {sd/1e9:.2f} km3 |")
    print(f"| Peak head decline | {(C.H_INIT - tr['head_final']).max():.1f} m |")
    print(f"| Peak subsidence | {tr['subsidence_final'].max()*100:.1f} cm "
          f"({tr['subsidence_final'].max()*100/C.NYEAR:.2f} cm/yr) |")
    print(f"| **Storage capacity destroyed permanently** | "
          f"**{perm/1e9:.3f} km3, {perm/sd*100:.1f}% of the water removed** |")
    print(f"| Irreversible share of peak subsidence | "
          f"{tr['inelastic_final'].max()/tr['subsidence_final'].max()*100:.0f}% |")
    print(f"| Observations | " + ", ".join(
        f"{k} {tr['obs_' + k].size}" for k in ("et", "grace", "insar", "head")) + " |")

    if ab:
        section("Ablation grid: what each observation is worth")
        print("Scored on district-annual abstraction against withheld truth. "
              "MAE in Mm3/yr.\n")
        print("| Observations | MAE | MAPE | bias | 50% | 80% | 90% | interval width |")
        print("|---|---:|---:|---:|---:|---:|---:|---:|")
        for k in ("BASELINE", "BASELINE_ORACLE", "PRIOR"):
            if k in ab:
                v = ab[k]
                cov = " | ".join(
                    [f"{v[f'cover_{l}']*100:.0f}%" if f"cover_{l}" in v else "none"
                     for l in (50, 80, 90)])
                w = f"{v['width90_mcm']:.1f}" if "width90_mcm" in v else "none"
                print(f"| {v['label']} | {v['mae_mcm']:.2f} | {v['mape_pct']:.1f}% | "
                      f"{v['bias_mcm']:+.2f} | {cov} | {w} |")
        for k in ORDER:
            if k not in ab:
                continue
            v = ab[k]
            print(f"| {LABEL[k]} | {v['mae_mcm']:.2f} | {v['mape_pct']:.1f}% | "
                  f"{v['bias_mcm']:+.2f} | "
                  + " | ".join([f"{v[f'cover_{l}']*100:.0f}%" for l in (50, 80, 90)])
                  + f" | {v['width90_mcm']:.1f} |")
        if "H" in ab and "BASELINE" in ab:
            r = ab["BASELINE"]["mae_mcm"] / ab["H"]["mae_mcm"]
            ro = ab["BASELINE_ORACLE"]["mae_mcm"] / ab["H"]["mae_mcm"]
            print(f"\nThe closure reduces the error of the published open-loop account "
                  f"by a factor of **{r:.1f}**, and of the same form with its efficiency "
                  f"fitted against the answer by a factor of **{ro:.1f}**.")

        section("What the observation set could not resolve")
        print("| Observations | directions resolved to 90% | unresolved | effective dimension |")
        print("|---|---:|---:|---:|")
        for k in ORDER:
            if k in ab and "n_resolved_90" in ab[k]:
                v = ab[k]
                print(f"| {LABEL[k]} | {v['n_resolved_90']} | {v['n_unresolved']} | "
                      f"{v['effective_dim']:.1f} |")
        print(f"\nOut of {C.NDIST * C.NYEAR} directions of the district-year abstraction "
              f"vector.")

        section("Recovery of the quantities the open-loop method assumes")
        print("| Observations | consumptive fraction MAE | pre-canopy share MAE | "
              "preconsolidation offset |")
        print("|---|---:|---:|---:|")
        for k in ORDER:
            if k in ab and "eta_mae" in ab[k]:
                v = ab[k]
                print(f"| {LABEL[k]} | {v['eta_mae']:.3f} | {v['preplant_mae']:.3f} | "
                      f"{v['pcs_offset_hat']:.2f} m against 12.00 m |")

    if eb:
        section("Error budget")
        print("Observations are weighted at instrument error. The structural error of "
              "the coarse\nforward model is estimated after the fact from the "
              "full-information residual.\n")
        print("| Leg | instrument | residual | structural | lag-1 | independence inflation |")
        print("|---|---:|---:|---:|---:|---:|")
        for k, v in eb.items():
            print(f"| {k} | {v['nominal']:.4g} | {v['residual_rms']:.4g} | "
                  f"{v['structural']:.4g} | {v['lag1']:.2f} | "
                  f"{v['independence_inflation']:.2f} |")
        print("\nOn every leg the structural component comes out below the instrument "
              "error, so no inflation is applied.")

    if cv:
        section("Convergence")
        print("| iteration | MAE | bias | 90% coverage | interferometry | heads | gravity |")
        print("|---:|---:|---:|---:|---:|---:|---:|")
        for r in cv:
            print(f"| {r['iter']:.0f} | {r['mae_mcm']:.2f} | {r['bias_mcm']:+.2f} | "
                  f"{r['cover_90']*100:.0f}% | {r['insar']*1000:.2f} mm | "
                  f"{r['head']:.3f} m | {r['grace']:.1f} mm |")

    if al:
        section("Decision layer")
        print(f"Zones: {al['zones']} drawdown strata. Time invariance of the response "
              f"matrix: mean worst-case error {al['lti_mean_max_rel_error']*100:.1f}% of "
              f"the pulse response.\n")
        print(f"Permanent loss already taken over the record: "
              f"{al['hist_permanent_loss_mcm']:.0f} Mm3.\n")
        print("**How much can be taken.** Permanent storage loss over the next twenty "
              "years, in full MODFLOW across the posterior.\n")
        print("| delivered, km3 | cut | mean loss, Mm3 | 10th | 90th |")
        print("|---:|---:|---:|---:|---:|")
        for f in al["frontier"]:
            print(f"| {f['delivered_km3']:.2f} | {f['cut']*100:.0f}% | "
                  f"{f['mean_mcm']:.0f} | {f['p10_mcm']:.0f} | {f['p90_mcm']:.0f} |")
        print(f"\nCutting delivery by "
              f"{al['frontier'][0]['delivered_km3']-al['frontier'][-1]['delivered_km3']:.2f} "
              f"km3 over the horizon avoids "
              f"{al['frontier'][0]['mean_mcm']-al['frontier'][-1]['mean_mcm']:.0f} Mm3 of "
              f"permanent capacity loss: "
              f"**{al['marginal_capacity_per_km3']:.0f} Mm3 of capacity per km3 not taken.**")
        print("\n**How it should be spread**, at equal delivered water.\n")
        print("| policy | delivered, km3 | surrogate 90% tail | MODFLOW 90% tail | discrepancy |")
        print("|---|---:|---:|---:|---:|")
        for k in ("uniform", "risk_bounded", "chance_constrained"):
            if k in al:
                v = al[k]
                d = v["simulator"]["cvar90_mcm"]
                print(f"| {k.replace('_',' ')} | {v['delivered_km3']:.2f} | "
                      f"{v['loss_cvar90_mcm']:.0f} | {d:.0f} | "
                      f"{(v['loss_cvar90_mcm']-d)/d*100:+.0f}% |")
        print(f"\nReallocating at equal delivered water changes permanent loss at the "
              f"90 per cent tail by **{al['reallocation_gain_pct']:+.1f}%**. Within "
              f"realistic bounds the distribution is not the lever; the total is.")

    if vo:
        section("Value of information")
        for f in ("fc_q_last5", "fc_perm_loss"):
            if f not in vo:
                continue
            v = vo[f]
            name = ("basin abstraction over the last five years" if f == "fc_q_last5"
                    else "storage capacity destroyed permanently")
            print(f"\n**Forecast: {name}.** Prior standard deviation "
                  f"{v['prior_sd']:.4g}, posterior {v['posterior_sd']:.4g}.\n")
            print("| rank | instrument | uncertainty removed |")
            print("|---:|---|---:|")
            for i, c in enumerate(v["top_candidates"][:8]):
                print(f"| {i+1} | {c['name']} | {c['sd_removed']:.4g} |")
            cur = v["greedy_curve"]
            print(f"\nForward selection of {len(cur)-1} instruments takes the posterior "
                  f"standard deviation from {cur[0]:.4g} to {cur[-1]:.4g}, a "
                  f"**{(1-cur[-1]/cur[0])*100:.0f}% reduction**.")
        if "pyemu_check" in vo and "error" not in vo["pyemu_check"]:
            print("\nSchur complement cross-checked against pyEMU: " + ", ".join(
                f"{k} relative difference {v['rel_diff']:.1e}"
                for k, v in vo["pyemu_check"].items()) + ".")

    if de:
        section("Detecting abstraction no evapotranspiration product can see")
        print(f"A withdrawal of {de['hidden_mcm_per_year']:.0f} Mm3/yr with no canopy, "
              f"and therefore no evapotranspiration signature, was planted in district "
              f"D{de['hidden_district']}: "
              f"{de['hidden_share_of_district']*100:.0f}% of that district's abstraction.\n")
        print(f"- The open-loop account attributes "
              f"**{de['open_loop_recovery_pct']:.0f}%** of that district's true "
              f"abstraction. It cannot see the withdrawal at all.")
        print(f"- The closure attributes **{de['closure_recovery_pct']:.0f}%**.")
        print(f"- On the ratio of closure estimate to what consumptive use can explain, "
              f"the district sits **{de['z_score']:.1f} standard deviations** above every "
              f"other district.")
        print(f"- Basin-wide error: closure {de['closure']['mae_mcm']:.2f} Mm3/yr against "
              f"{de['open_loop']['mae_mcm']:.2f} for the open-loop account.")

    seeds = {s: load(f"ablation_seed{s}.json") for s in (6, 7)}
    seeds = {s: v for s, v in seeds.items() if v}
    eu = load("ablation_etauniform.json")
    if seeds or eu:
        section("Robustness")

    if seeds:
        print("The rows that carry the argument, repeated on independent prior "
              "ensembles and independent ES-MDA perturbations. One seed is not "
              "evidence; the spread is what the difference between two rows has to "
              "beat.\n")
        rows = [k for k in ("H", "G", "SAT", "ET") if k in ab]
        print("| observations | " + " | ".join(f"seed {s}" for s in [5] + list(seeds))
              + " | mean | spread |")
        print("|---|" + "---:|" * (len(seeds) + 3))
        for k in rows:
            vals = [ab[k]["mae_mcm"]] + [seeds[s][k]["mae_mcm"] for s in seeds
                                         if k in seeds[s]]
            a = np.array(vals)
            print(f"| {LABEL[k]} | " + " | ".join(f"{v:.2f}" for v in vals)
                  + f" | **{a.mean():.2f}** | {a.max()-a.min():.2f} |")
        print("\nDifferences smaller than the spread in this table are not claimed.")

    if eu:
        print("\n**A truth with no district spread in the consumptive fraction.** Every "
              "district given the same fraction, 0.79, which is the case most favourable "
              "to the open-loop form.\n")
        print("| truth | open loop at 0.80 | open loop, constant fitted | closure |")
        print("|---|---:|---:|---:|")
        print(f"| districts differ, 0.69 to 0.88 | {ab['BASELINE']['mae_mcm']:.2f} | "
              f"{ab['BASELINE_ORACLE']['mae_mcm']:.2f} | "
              f"**{ab['H']['mae_mcm']:.2f}** |")
        print(f"| every district identical | {eu['BASELINE']['mae_mcm']:.2f} | "
              f"{eu['BASELINE_ORACLE']['mae_mcm']:.2f} | "
              f"**{eu['H']['mae_mcm']:.2f}** |")

    ks = load("kansas.json")
    if ks:
        m = ks["_meta"]
        section("L2 Kansas: against real metered abstraction")
        print(f"Six counties of the Northwest Kansas groundwater management district "
              f"over the Ogallala, {m['years'][0]} to {m['years'][1]}, "
              f"{m['irrigated_km2']:,.0f} km2 irrigated. The scored quantity is "
              f"county-annual abstraction against **per-water-right metered pumping** "
              f"published by the Kansas Department of Agriculture: "
              f"{m['n_rights']:,} water rights, of which {m['n_missing']} could not be "
              f"read.\n")
        print(f"The estimator sees {m['n_obs_head']:,} well-year head anomalies from "
              f"{m['n_wells']} wells and {6 * (m['years'][1]-m['years'][0]+1)} "
              f"county-year evapotranspiration volumes. It never sees the meters.\n")
        print("| observations available to the estimator | MAE, Mm3/yr | MAPE | "
              "90% coverage |")
        print("|---|---:|---:|---:|")
        for k in ("PRIOR", "BASELINE", "BASELINE_ORACLE", "ET", "H", "ETH"):
            if k not in ks:
                continue
            v = ks[k]
            cov = f"{v['cover_90']*100:.0f}%" if "cover_90" in v else "none produced"
            star = "**" if k == "ETH" else ""
            print(f"| {star}{v['label']}{star} | {star}{v['mae_mcm']:.2f}{star} | "
                  f"{star}{v['mape_pct']:.1f}%{star} | {cov} |")
        if "ETH" in ks:
            e = ks["ETH"]
            print(f"\nPosterior nuisances: specific yield {e['sy_hat']:.3f}, saturated "
                  f"thickness {e['bsat_hat']:.0f} m, recharge {e['rch_hat']:.0f} mm/yr, "
                  f"consumptive fraction by county " +
                  ", ".join(f"{c} {v:.2f}" for c, v in
                            zip(m["counties"], e["eta_hat"])) + ".")

    print("\n---\n")
    print("Reproduce with `make all` from a fresh clone. `make test` runs the guards, "
          "`make robustness` the seed and uniform-efficiency repeats, and "
          "`make kansas-data && make kansas` the Kansas rung.")


if __name__ == "__main__":
    main()
